services:
  app:
    image: bloglist-front-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api
    container_name: bloglist-front-dev

  server:
    image: bloglist-backend-dev
    build:
      context: ./bloglist
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 3003:3003
    container_name: bloglist-backend-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-bloglist
    depends_on:
      - app
      - server
