services:
  app:
    image: bloglist-front-prod
    build:
      context: ./frontend
      #dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    #ports:
    #- 3000:3000
    #environment:
    #- REACT_APP_BACKEND_URL=http://localhost:8080/api
    container_name: bloglist-front-prod

  server:
    image: bloglist-backend-prod
    build:
      context: ./bloglist
      #dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist:/usr/src/app
      - /usr/src/app/node_modules/
    #ports:
    #- 3003:3003
    container_name: bloglist-backend-prod

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-bloglist-prod
    depends_on:
      - app
      - server
